//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsPlannerMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public System.Guid Id { get; set; }
        public System.Guid Idea { get; set; }
        public System.Guid VoteCode { get; set; }
        public System.Guid Voter { get; set; }
    
        public virtual Idea Idea1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual VoteCode VoteCode1 { get; set; }
    }
}
